version: '3'
services:
  mindmap:
    container_name: mindmap
    image: mindmap:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/mindmap_back
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
      POSTGRES_USER: mindmap
      POSTGRES_PASSWORD: mindmap

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mindmap
      POSTGRES_PASSWORD: mindmap
      POSTGRES_DB: mindmap_dev
      POSTGRES_PORT: 5433
    command: -p 5433

volumes:
  postgres_data:

networks:
  default:
    name: mindmap-network
